Repository dnd-side-project/dnd-8th-3-backend, pull requests merged in 2023-02, with the labels that each got.

#1 초기셋팅[빈껍데기]하기
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/d83t/bpmbackend/BpmBackendApplication.java
  src/main/resources/application.properties
  src/test/java/d83t/bpmbackend/BpmBackendApplicationTests.java
Labels: documentation

#2 fix: 자카르타관련 빈 에러 발생하여, 의존성 수정
  build.gradle
  src/main/java/d83t/bpmbackend/config/OpenApiConfig.java
  src/main/resources/application.properties
Labels: documentation

#3 Chore: 배포 환경 세팅
  .github/workflows/deploy.yml
  Dockerfile
  config/nginx/Dockerfile
  config/nginx/default.conf
  config/scripts/docker-install.sh
  docker-compose.yml
Labels: documentation

#8 [D83T-21] 전역 예외처리 추가
  src/main/java/d83t/bpmbackend/exception/CustomException.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/main/java/d83t/bpmbackend/exception/ErrorResponse.java
  src/main/java/d83t/bpmbackend/exception/GlobalExceptionHandler.java
Labels: feature

#7 [D83T-16] 카카오 로그인 API 구현
  .gitignore
  src/main/java/d83t/bpmbackend/base/entity/DateEntity.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/entity/Profile.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/UserRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
Labels: feature

#9 D83T-18: 카카오 id 조회 서비스 구현
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/UserRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java
Labels: feature

#10 D83T-31
  build.gradle
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/repository/ProfileRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/UserServiceDetail.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/main/java/d83t/bpmbackend/security/WebConfig.java
  src/main/java/d83t/bpmbackend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/d83t/bpmbackend/security/jwt/JwtConfig.java
  src/main/java/d83t/bpmbackend/security/jwt/JwtService.java
Labels: feature

#11 [D83T-26] S3업로드 서비스 구현
  .gitignore
  build.gradle
  src/main/java/d83t/bpmbackend/config/S3Config.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
Labels: feature

#12 D83T-36 내눈바디 등록하기 API 구현
  src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/entity/BodyShape.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/entity/BodyShapeImage.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/repository/BodyShapeRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/entity/Profile.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/UserServiceDetail.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/main/java/d83t/bpmbackend/s3/S3UploaderService.java
  src/main/java/d83t/bpmbackend/s3/S3UploaderServiceImpl.java
  src/main/java/d83t/bpmbackend/security/jwt/JwtService.java
  src/main/java/d83t/bpmbackend/utils/FileUtils.java
Labels: feature

#13 [D83T-37] 내 눈바디 기록하기 리스트 조회 API 구현
  src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/repository/BodyShapeRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeServiceImpl.java
Labels: enhancement

#16 [D83T-42] 위치 등록 API 및 스튜디오 등록 API 구현
  src/main/java/d83t/bpmbackend/domain/aggregate/location/controller/LocationController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/entity/Location.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/repository/LocationRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioCreateRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/StudioImage.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
Labels: feature
