Repository dnd-side-project/dnd-8th-3-backend, pull requests merged in 2023-03, with the labels that each got.

#15 D83T-41 내 눈바디 삭제 API 구현
  src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/service/BodyShapeServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
Labels: enhancement

#19 [D83T-43] 상세 페이지 조회 API
  src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioCreateRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
Labels: enhancement, feature

#20 [D83T-49] SignUp API 리팩터링 docs 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/UserRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
Labels: documentation

#21 [D83T-49] signUp부분 request 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
Labels: documentation

#22 [D83T-49] request 원복
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
Labels: documentation

#23 [D83T-49] S3 이미지 경로를 반환하도록 수정, uuid비교 로직 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/s3/S3UploaderService.java
  src/main/java/d83t/bpmbackend/s3/S3UploaderServiceImpl.java
Labels: documentation

#17 D83T-46 일정등록하기 API
  build.gradle
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/Schedule.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/test/java/d83t/bpmbackend/config/WithAuthUser.java
  src/test/java/d83t/bpmbackend/config/WithAuthUserSecurityContextFactory.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImplTest.java
Labels: enhancement

#18 D83T-47 스케줄 조회 api 작성
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/Schedule.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/User.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImplTest.java
Labels: enhancement

#24 [D83T-50] 스케줄, 내눈바디 관련 docs수정
  src/main/java/d83t/bpmbackend/domain/aggregate/community/controller/BodyShapeController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/community/dto/BodyShapeResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/controller/UserController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleRequest.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/ScheduleResponse.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/dto/UserRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/controller/UserControllerTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImplTest.java
Labels: documentation

#26 [D83T-53] 내 일정등록할때 스튜디오 이름 없어도 받게끔 변경
  src/main/java/d83t/bpmbackend/domain/aggregate/user/entity/Schedule.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
Labels: fix

#27 [D83T-40] 리뷰 조회 API 추가
  src/main/java/d83t/bpmbackend/domain/aggregate/location/entity/Location.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/ReviewImage.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/StudioImage.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/ReviewRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
Labels: feature

#28 [D83T-44] 리뷰 좋아요 등록 및 삭제 API
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/entity/Profile.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Like.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/LikeRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
Labels: feature

#29 [D83T-42] 위치 등록 및 스튜디오 등록 합치도록 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/location/controller/LocationController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/dto/LocationResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/entity/Location.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/repository/LocationRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/location/service/LocationServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
Labels: fix

#30 [D83T-57] 스튜디오 전체 리스트 조회 API 추가
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/repository/StudioRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
  src/test/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepositoryTest.java
Labels: enhancement

#31 [D83T-57] 스튜디오 전체 리스트 조회 API 에 갯수 추가
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/controller/StudioController.java
Labels: enhancement

#32 [D83T-56] 추천해요 로직 추가
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/ReviewResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioRequestDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/dto/StudioResponseDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Review.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/StudioServiceImpl.java
Labels: feature

#33 [D83T-64] User, Schedule관련 리팩터링, 일정 중복등록 에러 해결
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/dto/ProfileDto.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageService.java
  src/main/java/d83t/bpmbackend/domain/aggregate/profile/service/ProfileImageServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/ScheduleRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/repository/UserRepository.java
  src/main/java/d83t/bpmbackend/domain/aggregate/user/service/UserServiceImpl.java
  src/main/java/d83t/bpmbackend/exception/Error.java
Labels: fix

#34 hotfix: 리뷰 등록시 이미지 경로 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
Labels: fix

#35 hotfix: 중복 생성 이슈 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/LikeServiceImpl.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
Labels: fix

#36 hotfix: 리뷰 등록 시 id null 이슈 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/entity/Studio.java
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
Labels: fix

#37 hotfix: 리뷰 등록 이슈 수정
  src/main/java/d83t/bpmbackend/domain/aggregate/studio/service/ReviewServiceImpl.java
Labels: fix
